package com.oguzguven.portfolio.contact;
import jakarta.persistence.*;
@Entity @Table(name="contact_content") public class Contact {
 @Id private Long id=1L;
 @Column(nullable=false,length=80) private String eyebrow; @Column(nullable=false,length=100) private String kicker;
 @Column(name="title_prefix",nullable=false,length=120) private String titlePrefix; @Column(name="title_highlight",nullable=false,length=80) private String titleHighlight;
 @Column(nullable=false,length=1200) private String description;
 @Column(name="github_url",nullable=false,length=500) private String githubUrl; @Column(name="github_label",nullable=false,length=200) private String githubLabel;
 @Column(name="linkedin_url",nullable=false,length=500) private String linkedinUrl; @Column(name="linkedin_label",nullable=false,length=200) private String linkedinLabel;
 @Column(nullable=false,length=200) private String email; @Column(name="email_label",nullable=false,length=100) private String emailLabel;
 @Column(name="form_subject",nullable=false,length=200) private String formSubject; @Column(name="name_placeholder",nullable=false,length=120) private String namePlaceholder;
 @Column(name="email_placeholder",nullable=false,length=120) private String emailPlaceholder; @Column(name="message_placeholder",nullable=false,length=250) private String messagePlaceholder;
 @Column(name="submit_text",nullable=false,length=80) private String submitText; @Column(name="success_message",nullable=false,length=300) private String successMessage; @Column(name="error_message",nullable=false,length=300) private String errorMessage;
 @Column(name="footer_name",nullable=false,length=100) private String footerName; @Column(name="footer_role",nullable=false,length=100) private String footerRole; @Column(name="footer_location",nullable=false,length=100) private String footerLocation; @Column(name="footer_copyright",nullable=false,length=80) private String footerCopyright;
 protected Contact(){} public Contact(ContactRequest r){update(r);} public void update(ContactRequest r){eyebrow=r.eyebrow();kicker=r.kicker();titlePrefix=r.titlePrefix();titleHighlight=r.titleHighlight();description=r.description();githubUrl=r.githubUrl();githubLabel=r.githubLabel();linkedinUrl=r.linkedinUrl();linkedinLabel=r.linkedinLabel();email=r.email();emailLabel=r.emailLabel();formSubject=r.formSubject();namePlaceholder=r.namePlaceholder();emailPlaceholder=r.emailPlaceholder();messagePlaceholder=r.messagePlaceholder();submitText=r.submitText();successMessage=r.successMessage();errorMessage=r.errorMessage();footerName=r.footerName();footerRole=r.footerRole();footerLocation=r.footerLocation();footerCopyright=r.footerCopyright();}
 public String getEyebrow(){return eyebrow;}public String getKicker(){return kicker;}public String getTitlePrefix(){return titlePrefix;}public String getTitleHighlight(){return titleHighlight;}public String getDescription(){return description;}public String getGithubUrl(){return githubUrl;}public String getGithubLabel(){return githubLabel;}public String getLinkedinUrl(){return linkedinUrl;}public String getLinkedinLabel(){return linkedinLabel;}public String getEmail(){return email;}public String getEmailLabel(){return emailLabel;}public String getFormSubject(){return formSubject;}public String getNamePlaceholder(){return namePlaceholder;}public String getEmailPlaceholder(){return emailPlaceholder;}public String getMessagePlaceholder(){return messagePlaceholder;}public String getSubmitText(){return submitText;}public String getSuccessMessage(){return successMessage;}public String getErrorMessage(){return errorMessage;}public String getFooterName(){return footerName;}public String getFooterRole(){return footerRole;}public String getFooterLocation(){return footerLocation;}public String getFooterCopyright(){return footerCopyright;}
}
