import {useEffect,useMemo,useState} from "react";
import {createTechnology,deleteTechnology,getTechnologies,toggleTechnologyPublication,updateTechnology} from "../services/technologyApi";
import {uploadMedia} from "../services/mediaApi";
const empty={name:"",slug:"",iconUrl:"",color:"#ffffff",published:true,displayOrder:1};

function Modal({value,mode,onClose,onSave}){
 const[draft,setDraft]=useState(value),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState("");
 const change=e=>{const{name,value:next,type,checked}=e.target;setDraft(old=>({...old,[name]:type==="checkbox"?checked:next}));};
 const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);setError("");try{const media=await uploadMedia(file);setDraft(old=>({...old,iconUrl:media.url}));}catch(err){setError(err.message);}finally{setUploading(false);}};
 const submit=async e=>{e.preventDefault();setSaving(true);setError("");try{await onSave(draft);onClose();}catch(err){setError(err.message);}finally{setSaving(false);}};
 const preview=draft.iconUrl||`https://cdn.simpleicons.org/${draft.slug}`;
 return <div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="admin-project-editor admin-technology-modal"><header className="admin-project-editor__header"><div><span className="admin-kicker">TECHNOLOGY EDITOR</span><h2>{mode==="create"?"Teknoloji ekle":"Teknolojiyi düzenle"}</h2><p>Teknoloji bandındaki isim, logo, renk ve görünürlüğü yönetin.</p></div><button className="admin-modal-close" onClick={onClose}>×</button></header><form className="admin-project-editor__form" onSubmit={submit}><div className="admin-project-editor__fields">
 <label>Teknoloji adı<input name="name" value={draft.name} onChange={change} required/></label><label>Simple Icons slug<input name="slug" value={draft.slug} onChange={change} placeholder="springboot" required/></label><label>Vurgu rengi<input name="color" type="color" value={draft.color||"#ffffff"} onChange={change}/></label><label>Sıra<input name="displayOrder" type="number" min="1" value={draft.displayOrder} onChange={e=>setDraft(old=>({...old,displayOrder:Number(e.target.value)}))}/></label>
 <label className="admin-image-upload wide"><input type="file" accept="image/*,.svg" onChange={upload}/><span className="admin-image-upload__icon">＋</span><span><strong>Özel logo yükle</strong><small>{uploading?"Yükleniyor...":"Yüklemezsen Simple Icons slug kullanılır."}</small></span><b>{uploading?"Bekleyin":"Dosya seç"}</b></label><label className="admin-editor-publish wide"><input name="published" type="checkbox" checked={draft.published} onChange={change}/><span><i/></span><div><strong>Teknolojiyi yayınla</strong><small>Kapalı olduğunda teknoloji bandında görünmez.</small></div></label></div>
 <aside className="admin-project-preview"><span className="admin-kicker">LIVE PREVIEW</span><div className="admin-technology-preview" style={{borderColor:draft.color}}><img src={preview} alt="" onError={e=>e.currentTarget.style.display="none"}/><strong>{draft.name||"Technology"}</strong></div><p>Logo için en pratik seçenek Simple Icons üzerindeki marka slug'ını kullanmaktır.</p></aside>
 <footer className="admin-project-editor__footer">{error&&<p className="admin-error">{error}</p>}<button type="button" onClick={onClose} disabled={uploading}>Vazgeç</button><button className="admin-primary" disabled={saving||uploading}>{uploading?"Logo yükleniyor...":saving?"Kaydediliyor...":"Kaydet"}</button></footer></form></section></div>;
}

export default function TechnologyManager(){
 const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[editing,setEditing]=useState(null),[creating,setCreating]=useState(false);
 const ordered=useMemo(()=>[...items].sort((a,b)=>a.displayOrder-b.displayOrder),[items]);
 const load=()=>{setLoading(true);setError("");getTechnologies().then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));};useEffect(load,[]);
 const add=async value=>{const displayOrder=items.length?Math.max(...items.map(i=>i.displayOrder))+1:1;const saved=await createTechnology({...value,displayOrder});setItems(old=>[...old,saved]);};
 const update=async value=>{const saved=await updateTechnology(editing.id,value);setItems(old=>old.map(i=>i.id===saved.id?saved:i));};
 const remove=async item=>{if(!window.confirm(`“${item.name}” silinsin mi?`))return;await deleteTechnology(item.id);setItems(old=>old.filter(i=>i.id!==item.id));};
 const toggle=async item=>{const saved=await toggleTechnologyPublication(item.id);setItems(old=>old.map(i=>i.id===saved.id?saved:i));};
 return <section className="admin-card admin-content-card admin-projects-card"><div className="admin-card__head admin-projects-head"><div><span className="admin-kicker">TECH STACK</span><h3>Technologies</h3><p>Teknoloji bandındaki araçları, logoları ve sıralamayı yönetin.</p></div><button className="admin-primary" onClick={()=>setCreating(true)}>＋ Teknoloji ekle</button></div><div className="admin-projects-table"><div className="admin-projects-columns"><span>TEKNOLOJİ</span><span>SLUG / SIRA</span><span>YAYIN DURUMU</span><span>İŞLEMLER</span></div>
 {loading&&<div className="admin-projects-empty"><strong>Teknolojiler yükleniyor...</strong></div>}{error&&<div className="admin-projects-empty"><strong>Veriler getirilemedi</strong><small>{error}</small><button onClick={load}>Tekrar dene</button></div>}
 {!loading&&!error&&ordered.map(item=><article className="admin-project-row" key={item.id}><div className="admin-project-main"><span className="admin-tech-icon"><img src={item.iconUrl||`https://cdn.simpleicons.org/${item.slug}`} alt=""/></span><div><strong>{item.name}</strong><small>#{item.color?.replace("#","")||"default"}</small></div></div><span className="admin-project-type">{item.slug} · {String(item.displayOrder).padStart(2,"0")}</span><button className={`admin-publish-toggle ${item.published?"is-published":""}`} onClick={()=>toggle(item)}><span className="admin-publish-switch"><i/></span><span>{item.published?"Yayında":"Taslak"}</span></button><div className="admin-row-actions"><button onClick={()=>setEditing(item)}>Düzenle</button><button className="danger" onClick={()=>remove(item)}>Sil</button></div></article>)}</div>
 {creating&&<Modal mode="create" value={empty} onClose={()=>setCreating(false)} onSave={add}/>} {editing&&<Modal mode="edit" value={editing} onClose={()=>setEditing(null)} onSave={update}/>}</section>;
}
